CREATE TABLE user (
  username VARCHAR(50) NOT NULL PRIMARY KEY,
  email VARCHAR(50),
  password VARCHAR(500),
  activated BOOLEAN DEFAULT FALSE,
  activationkey VARCHAR(50) DEFAULT NULL,
  resetpasswordkey VARCHAR(50) DEFAULT NULL
);

CREATE TABLE authority (
  name VARCHAR(50) NOT NULL PRIMARY KEY
);

CREATE TABLE user_authority (
    username VARCHAR(50) NOT NULL,
    authority VARCHAR(50) NOT NULL,
    FOREIGN KEY (username) REFERENCES user (username),
    FOREIGN KEY (authority) REFERENCES authority (name),
    UNIQUE INDEX user_authority_idx_1 (username, authority)
);

CREATE TABLE oauth_access_token (
  token_id VARCHAR(256) DEFAULT NULL,
  token BLOB,
  authentication_id VARCHAR(256) DEFAULT NULL,
  user_name VARCHAR(256) DEFAULT NULL,
  client_id VARCHAR(256) DEFAULT NULL,
  authentication BLOB,
  refresh_token VARCHAR(256) DEFAULT NULL
);

CREATE TABLE oauth_refresh_token (
  token_id VARCHAR(256) DEFAULT NULL,
  token BLOB,
  authentication BLOB
);

create table employee(
    id BIGINT generated by default as identity,
    first_name VARCHAR(256),
    last_name VARCHAR(256),
    user_name VARCHAR(256)
);

create table tweet(
    id BIGINT generated by default as identity,
    entry VARCHAR(256),
    hashtag VARCHAR(50),
    employee_id BIGINT,
    last_modified_at timestamp DEFAULT CURRENT_TIMESTAMP,
    foreign key(employee_id) references employee(id)
);

create table follower(
    id  BIGINT generated by default as identity,
    employee_id BIGINT,
    follower_id BIGINT,
    foreign key(employee_id) references employee(id),
    foreign key(follower_id) references employee(id)
)